### GET all users for mocks
GET http://localhost:3123/userById

###
### GET a specific user by ID
GET http://localhost:3123/userById/1

###
### GET all offers for mocks
GET http://localhost:3123/offers

###
### GET all cities for mocks
GET http://localhost:3123/cityById

###
### GET a specific city by ID
GET http://localhost:3123/cityById/Paris

###
### GET all property types for mocks
GET http://localhost:3123/propertyTypes

###
### GET all conveniences for mocks
GET http://localhost:3123/conveniences

###
